name: "Delete All Closed Issues"

on: [workflow_dispatch]

permissions:
  issues: write
  contents: read

jobs:
  delete-closed-issues:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y    

    - name: Delete all closed issues
      run: |
        echo "Fetching closed issues..."
        closed_issues=$(gh issue list --state closed --json number --jq '.[].number')
        
        if [ -z "$closed_issues" ]; then
          echo "No closed issues found."
        else
          echo "Found closed issues: $closed_issues"
          for issue in $closed_issues; do
            echo "Deleting issue #$issue..."
            gh api repos/:owner/:repo/issues/$issue -X DELETE || echo "Failed to delete issue #$issue (might not have permission)"
          done
          echo "Finished deleting closed issues."
        fi
