name: "Run TODO to Issue"

on: [push]

permissions:
  issues: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y    

    - name: Set script to executable
      run: chmod +x .github/scripts/todo_fixme_to_issues.sh

    - name: Find TODOs and create issues
      run: .github/scripts/todo_fixme_to_issues.sh TODO enhancement

    - name: Find BUGs and create issues
      run: .github/scripts/todo_fixme_to_issues.sh FIXME bug


